import { PERPLEXITY_API_KEY, GEMINI_API_KEY } from '../data/constants';

export const sendChatMessage = async (message) => {
  try {
    // Placeholder: Replace with actual API call to Perplexity or Gemini
    // For now, return a mock response
    return {
      success: true,
      response: `This is a mock response to: "${message}". In production, this will connect to Perplexity or Gemini API.`,
      timestamp: new Date().toISOString()
    };
  } catch (error) {
    return { success: false, error: error.message };
  }
};

export const generatePrompt = async (topic) => {
  try {
    // Placeholder for prompt generation API
    return {
      success: true,
      prompt: `Sample prompt about ${topic}. This will be generated by Perplexity or Gemini in production.`,
      timestamp: new Date().toISOString()
    };
  } catch (error) {
    return { success: false, error: error.message };
  }
};
